Various fixes (#11)
- Improved usability and performance of the support scripts
- Upgraded kcov and shellcheck to the latest version
- Cleaned up and improved documentation
- Simplified entry points
- Fixed CI pipeline
- Added probot configuration files

diff --git a/bin/docker b/bin/docker
--- a/bin/docker
+++ b/bin/docker
@@ -2,42 +2,85 @@
 
 __help() {
 cat <<END_OF_HELP
-Usage: ${0} <commands> [options]
-where 'commands' are one of the following:
+Usage: ${0} <commands> [options]                  <> - required parameters
+Where commands are:                               [] - optional parameters
 
-  build  -   options are passed to 'docker image build'.
-             See 'docker image build --help' for a full list of options.
+  build [image:]<tag> [docker-build-options]
+            Builds a new container image using 'docker image build' command.
+            See 'docker image build --help' for a list of supported options.
 
-  run    -   apart for the following exceptions, all options are passed as
-             arguments to './bin/test' running inside the container:
+  run [image:]<tag> [shell-command-and-options]
+            Run a command in a new container with 'docker container run'.
+            Container-run options are preconfigured, user input is executed.
 
-             - l   run docker container and open a login shell
+  attach [image:]<tag> [docker-attach-options]
+            Attaches input/output streams to an already running container.
+            See 'docker container attach --help' for all supported options.
+
+  exec [image:]<tag> [shell-command-and-options]
+            Executes a command in a container which launched from the image.
+            See 'docker container exec --help' for more information.
+
+  stop [image:]<tag> [docker-stop-options]
+            Stops all running containers based on the application's image.
+            See 'docker container stop --help' for more information.
 
 END_OF_HELP
 }
 
-GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
-: "${GIT_BRANCH:=unknown}"
+COMMAND="${1:-help}"
+if [[ -z "${2}" || "${2}" == '-'* ]]; then
+  IMAGE="$(echo "${PWD##*/}" | tr '[:upper:] ' '[:lower:]-')"
+  TAG="latest"
+  shift 1
+elif [[ "${2}" == *':'* ]]; then
+  IMAGE="${2}"
+  TAG="${2##*:}"
+  shift 2
+elif [[ "${2}" == *'/'* ]]; then
+  IMAGE="${2}"
+  TAG="latest"
+  shift 2
+elif [[ -n "${2}" ]]; then
+  IMAGE="$(echo "${PWD##*/}" | tr '[:upper:] ' '[:lower:]-'):${2}"
+  TAG="${2}"
+  shift 2
+else
+  echo "Invalid argument -- ${2}" >&2
+  echo "  - IMAGE: ${IMAGE}" >&2
+  echo "  - TAG:   ${TAG}" >&2
+  exit 1
+fi
 
-[[ "${GIT_BRANCH}" == 'master' ]] && TAG='' || TAG=":${GIT_BRANCH}"
-
-CONTAINER="umkadk/getopts_long${TAG}"
-CMD="${1}" && shift
-
-case "${CMD}" in
+case "${COMMAND}" in
   'b'|'build')
-    if [[ -z "${*}" ]]; then docker image build --tag "${CONTAINER}" "${PWD}"
-    else docker image build "${@}" --tag "${CONTAINER}" "${PWD}"; fi
+    DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} \
+      docker image build --tag "${IMAGE}" --target "${TAG}" "${@}" "${PWD}";
     ;;
   'r'|'run')
-    docker container run --rm --init -it -v "${PWD}:/mnt" "${CONTAINER}" "${@}"
+    [[ -t 1 ]] && IT='-it' # Check if output is attached to a TTY
+    docker container run ${GITHUB_ACTIONS:+-u root} \
+      --rm --init ${IT} -v "${PWD}:/mnt" "${IMAGE}" "${@}"
     ;;
-  '')
-    __help >&2
-    exit 1
+  'a'|'attach')
+    CONTAINER_ID="$(docker container ls -qlf "ancestor=${IMAGE}")"
+    docker container attach "${@}" "${CONTAINER_ID}"
+    ;;
+  'e'|'exec')
+    [[ -t 1 ]] && IT='-it' # Check if output is attached to a TTY
+    CONTAINER_ID="$(docker container ls -qlf "ancestor=${IMAGE}")"
+    docker container exec ${IT} "${CONTAINER_ID}" "${@}"
+    ;;
+  's'|'stop')
+    CONTAINER_IDS="$(docker container ls -qf "ancestor=${IMAGE}")"
+    [[ -n "${CONTAINER_IDS}" ]] && docker container stop "${@}" "${CONTAINER_IDS}"
+    ;;
+  '-?'|'--help'|'help')
+    __help
+    exit
     ;;
   *)
-    echo "${0}: Unknown command -- ${CMD}" >&2
+    echo "${0}: Unknown command -- ${DOCKER_CMD}" >&2
     exit 1
     ;;
 esac
diff --git a/bin/kcov b/bin/kcov
--- a/bin/kcov
+++ b/bin/kcov
@@ -2,10 +2,9 @@
 
 set -e
 
-: "${GETOPTS_LONG_BIN:=./bin}"
-: "${GETOPTS_LONG_LIB:=./lib}"
-: "${GETOPTS_LONG_TEST:=./test}"
-: "${GETOPTS_LONG_COVERAGE:=./coverage}"
+: "${LIB_DIR:="./lib"}"
+: "${TEST_DIR:="./test"}"
+: "${COVERAGE_DIR:="./coverage"}"
 
 __exit() {
   echo "${0}: ${1:?Missing required parameter -- error message}" >&2
@@ -27,11 +26,9 @@ color_diff() {
 print_coverage_diff() {
   : "${1:?Missing required argument -- new code coverage}"
 
-  local sha
+  local sha coverage diff
   sha="$(head -c7 /home/VERSION)"
-  local coverage
   coverage="$(jq -r .percent_covered "/home/coverage/coverage.json")"
-  local diff
   diff=$(echo "${coverage} - ${1}" | bc -l)
 
   if tty -s && [[ "${diff}" -gt '0' ]]; then color_diff 32 "${diff}" "${sha}"
@@ -40,31 +37,44 @@ print_coverage_diff() {
   else printf "%+.2f%% compared to %s" "${diff}" "${sha}"; fi
 }
 
-path_exists "${GETOPTS_LONG_LIB}"
-path_exists "${GETOPTS_LONG_TEST}"
+die_with_kcov_user_error() {
+cat <<EOS >&2 && exit 1
+ERROR: kcov can't be run as root -- all fallback strategies failed:
 
-# Run shellcheck
-echo "Checking shell code: ${GETOPTS_LONG_LIB} ${GETOPTS_LONG_TEST} ${GETOPTS_LONG_BIN}"
-shellcheck -f tty -s bash -a \
-  "${GETOPTS_LONG_LIB}"/* \
-  "${GETOPTS_LONG_TEST}"/*.bash "${GETOPTS_LONG_TEST}"/bin/*  \
-  "${GETOPTS_LONG_BIN}"/*
+         - running as current user -- failed
+         - running as $0 owner -- failed
 
-# Run bats
-TEST_DIR=( "${@:-${GETOPTS_LONG_TEST}}" )
-echo "Running tests: ${TEST_DIR[*]} "
-bats --tap --recursive "${TEST_DIR[@]}"
-[ -n "${*}" ] && exit
+    Q: Why am I seeing this?
+    A: kcov collets coverage data by setting PS4 to a custom string.
+       But bash-4.3.42+ disables updating PS4 when running as root:
+
+         - https://bugzilla.redhat.com/show_bug.cgi?id=1379634
+
+       Try either running the script as non-privileged user, or set
+       the owner of $0 to non-root.
+EOS
+}
+
+path_exists "${LIB_DIR}"
+path_exists "${TEST_DIR}"
 
 # Setup exit trap
 TEMP_DIR="$(mktemp -d -t kcov.XXXXXXXXX)"
 trap 'rm -Rf ${TEMP_DIR}' EXIT
 
 # Run kcov
-echo "Generating coverage report: ${GETOPTS_LONG_COVERAGE}/index.html"
-kcov --clean --include-path="${GETOPTS_LONG_LIB}" \
-  "${TEMP_DIR}" \
-  bats --recursive "${GETOPTS_LONG_TEST}"
+echo "Generating coverage report: ${COVERAGE_DIR}/index.html"
+KCOV_CMD="/usr/local/bin/kcov --clean --include-path=${LIB_DIR} ${@} \
+  ${TEMP_DIR} /usr/local/bin/bats --recursive ${TEST_DIR}"
+if [[ ${EUID} -eq 0 ]]; then
+  KCOV_USER="$(ls -l "${0}" | awk '{print $3}')"
+  [[ "${KCOV_USER}" == "root" ]] && die_with_kcov_user_error
+
+  chown -R "${KCOV_USER}" "${TEMP_DIR}"
+  su -p "${KCOV_USER}" -c "${KCOV_CMD}"
+else
+  ${KCOV_CMD}
+fi
 
 # Clean up kcov report
 rm "${TEMP_DIR}"/bats/{bcov.css,amber.png,glass.png}
@@ -73,11 +83,11 @@ sed -i -E 's#/(home|mnt)/##g' \
   "${TEMP_DIR}"/bats/*.{json,xml} "${TEMP_DIR}"/bats/metadata/*
 
 # Present kcov report
-rm -Rf "${GETOPTS_LONG_COVERAGE}"
-cp -LR "${TEMP_DIR}/bats" "${GETOPTS_LONG_COVERAGE}"
+rm -Rf "${COVERAGE_DIR}"
+cp -LR "${TEMP_DIR}/bats" "${COVERAGE_DIR}"
 
 # Total code coverage
-COVERAGE="$(jq -r .percent_covered "${GETOPTS_LONG_COVERAGE}/coverage.json")"
+COVERAGE="$(jq -r .percent_covered "${COVERAGE_DIR}/coverage.json")"
 printf "Code covered: %s%% " "${COVERAGE}"
 
 # Code coverage diff
