Simplified shell env modifications

diff --git a/test/bin/getopts_long-without_extdebug-verbose b/test/bin/getopts_long-without_extdebug-verbose
--- a/test/bin/getopts_long-without_extdebug-verbose
+++ b/test/bin/getopts_long-without_extdebug-verbose
@@ -58,23 +58,17 @@ variables() {
     getopts_function -vuser_val1 --variable=user_val2 -- user_arg
 }
 
-enable_extdebug='false'
-if shopt -q extdebug; then
-    enable_extdebug='true'
+(
     shopt -u extdebug
-fi
 
-: "${1:?Missing required parameter -- function name}"
-function_name=${1}
-shift
+    : "${1:?Missing required parameter -- function name}"
+    function_name=${1}
+    shift
 
-if declare -f "$function_name" > /dev/null; then
-    ${function_name} "$@"
-else
-    echo "Function not found -- ${function_name}"
-    exit 1
-fi
-
-if ${enable_extdebug}; then
-    shopt -s extdebug
-fi
+    if declare -f "$function_name" > /dev/null; then
+        ${function_name} "$@"
+    else
+        echo "Function not found -- ${function_name}"
+        exit 1
+    fi
+)
